networks:
  traefik-proxy:
    external: true

services:
  syncthing:
    image: linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/US
    hostname: syncthing
    labels:
      traefik.enable: true
      traefik.docker.network: traefik-proxy
      traefik.http.routers.syncthing.entrypoints: http
      traefik.http.routers.syncthing.rule: Host(`syncthing.${TRAEFIK_BASE_DOMAIN:?TRAEFIK_BASE_DOMAIN is not set}`)
      traefik.http.middlewares.syncthing-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.syncthing.middlewares: syncthing-https-redirect
      traefik.http.routers.syncthing-secure.entrypoints: https
      traefik.http.routers.syncthing-secure.rule: Host(`syncthing.${TRAEFIK_BASE_DOMAIN:?TRAEFIK_BASE_DOMAIN is not set}`)
      traefik.http.routers.syncthing-secure.tls: true
      traefik.http.routers.syncthing-secure.tls.certresolver: cloudflare
      traefik.http.routers.syncthing-secure.service: syncthing
      traefik.http.services.syncthing.loadbalancer.server.port: 8384
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}:/config
      - ${DATA_DIR}:/DATA
    networks:
      - traefik-proxy
    privileged: false
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
